---
development:
  cloud_name: diyuhaftw
  api_key: '954522487732129'
  api_secret: Vl18JF_Qc9gL5uFbXlAcHgTNMrI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: diyuhaftw
  api_key: '954522487732129'
  api_secret: Vl18JF_Qc9gL5uFbXlAcHgTNMrI
  enhance_image_tag: true
  static_image_support: true
  secure: true
staging:
  cloud_name: diyuhaftw
  api_key: '954522487732129'
  api_secret: Vl18JF_Qc9gL5uFbXlAcHgTNMrI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: diyuhaftw
  api_key: '954522487732129'
  api_secret: Vl18JF_Qc9gL5uFbXlAcHgTNMrI
  enhance_image_tag: true
  static_image_support: false
