---
development:
  uri: "http://localhost:8000/faye"
  script: "http://localhost:8000/faye.js"
production:
  uri: "https://salty-bayou-1265.herokuapp.com/faye"
  script: "https://salty-bayou-1265.herokuapp.com/faye.js"
test:
  disabled: true
staging:
  uri: "https://salty-bayou-1265-647.herokuapp.com/faye"
  script: "https://salty-bayou-1265-647.herokuapp.com/faye.js"

