---
development:
  uri: "http://localhost:8000/faye"
  script: "http://localhost:8000/faye.js"
  password: "this_is_a_SeCRet"
production:
  uri: "https://salty-bayou-1265.herokuapp.com/faye"
  script: "https://salty-bayou-1265.herokuapp.com/faye.js"
  password: "this_is_a_SeCRet"
test:
  disabled: true
staging:
  password: "this_is_a_SeCRet"
  uri: "http://salty-bayou-1265-647.herokuapp.com/faye"
  script: "http://salty-bayou-1265-647.herokuapp.com/faye.js"

